build: Update Cargo (#388)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [reqwest](https://redirect.github.com/seanmonstar/reqwest) |
dependencies | minor | `0.12.24` → `0.13.0` |
|
[reqwest-middleware](https://redirect.github.com/TrueLayer/reqwest-middleware)
| dependencies | minor | `0.4.2` → `0.5.0` |
|
[reqwest-retry](https://redirect.github.com/TrueLayer/reqwest-middleware)
| dependencies | minor | `0.7.0` → `0.9.0` |
| [strum](https://redirect.github.com/Peternator7/strum) | dependencies
| minor | `0.27` → `0.28` |

---

### Release Notes

<details>
<summary>seanmonstar/reqwest (reqwest)</summary>

###
[`v0.13.2`](https://redirect.github.com/seanmonstar/reqwest/blob/HEAD/CHANGELOG.md#v0132)

[Compare
Source](https://redirect.github.com/seanmonstar/reqwest/compare/v0.13.1...v0.13.2)

- Fix HTTP/2 and native-tls ALPN feature combinations.
- Fix HTTP/3 to send h3 ALPN.
- (wasm) fix `RequestBuilder::json()` from override previously set
content-type.

###
[`v0.13.1`](https://redirect.github.com/seanmonstar/reqwest/blob/HEAD/CHANGELOG.md#v0131)

[Compare
Source](https://redirect.github.com/seanmonstar/reqwest/compare/v0.13.0...v0.13.1)

- Fixes compiling with rustls on Android targets.

###
[`v0.13.0`](https://redirect.github.com/seanmonstar/reqwest/blob/HEAD/CHANGELOG.md#v0130)

[Compare
Source](https://redirect.github.com/seanmonstar/reqwest/compare/v0.12.28...v0.13.0)

- **Breaking changes**:
  - `rustls` is now the default TLS backend, instead of `native-tls`.
- `rustls` crypto provider defaults to aws-lc instead of *ring*.
(`rustls-no-provider` exists if you want a different crypto provider)
  - `rustls-tls` has been renamed to `rustls`.
- rustls roots features removed, `rustls-platform-verifier` is used by
default.
    - To use different roots, call `tls_certs_only(your_roots)`.
- `native-tls` now includes ALPN. To disable, use `native-tls-no-alpn`.
  - `query` and `form` are now crate features, disabled by default.
- Long-deprecated methods and crate features have been removed (such as
`trust-dns`, which was renamed `hickory-dns` a while ago).
- Many TLS-related methods renamed to improve autocompletion and
discovery, but previous name left in place with a "soft" deprecation.
(just documented, no warnings)
  - For example, prefer `tls_backend_rustls()` over `use_rustls_tls()`.

#### v0.12.28

- Fix compiling on Windows if TLS and SOCKS features are not enabled.

#### v0.12.27

- Add `ClientBuilder::windows_named_pipe(name)` option that will force
all requests over that Windows Named Piper.

#### v0.12.26

- Fix sending `Accept-Encoding` header only with values configured with
reqwest, regardless of underlying tower-http config.

#### v0.12.25

- Add `Error::is_upgrade()` to determine if the error was from an HTTP
upgrade.
- Fix sending `Proxy-Authorization` if only username is configured.
- Fix sending `Proxy-Authorization` to HTTPS proxies when the target is
HTTP.
- Refactor internal decompression handling to use tower-http.

#### v0.12.24

- Refactor cookie handling to an internal middleware.
- Refactor internal random generator.
- Refactor base64 encoding to reduce a copy.
- Documentation updates.

#### v0.12.23

- Add `ClientBuilder::unix_socket(path)` option that will force all
requests over that Unix Domain Socket.
- Add `ClientBuilder::retry(policy)` and `reqwest::retry::Builder` to
configure automatic retries.
- Add `ClientBuilder::dns_resolver2()` with more ergonomic argument
bounds, allowing more resolver implementations.
- Add `http3_*` options to `blocking::ClientBuilder`.
- Fix default TCP timeout values to enabled and faster.
- Fix SOCKS proxies to default to port 1080
- (wasm) Add cache methods to `RequestBuilder`.

#### v0.12.22

- Fix socks proxies when resolving IPv6 destinations.

#### v0.12.21

- Fix socks proxy to use `socks4a://` instead of `socks4h://`.
- Fix `Error::is_timeout()` to check for hyper and IO timeouts too.
- Fix request `Error` to again include URLs when possible.
- Fix socks connect error to include more context.
- (wasm) implement `Default` for `Body`.

#### v0.12.20

- Add `ClientBuilder::tcp_user_timeout(Duration)` option to set
`TCP_USER_TIMEOUT`.
- Fix proxy headers only using the first matched proxy.
- (wasm) Fix re-adding `Error::is_status()`.

#### v0.12.19

- Fix redirect that changes the method to GET should remove payload
headers.
- Fix redirect to only check the next scheme if the policy action is to
follow.
- (wasm) Fix compilation error if `cookies` feature is enabled (by the
way, it's a noop feature in wasm).

#### v0.12.18

- Fix compilation when `socks` enabled without TLS.

#### v0.12.17

- Fix compilation on macOS.

#### v0.12.16

- Add `ClientBuilder::http3_congestion_bbr()` to enable BBR congestion
control.
- Add `ClientBuilder::http3_send_grease()` to configure whether to send
use QUIC grease.
- Add `ClientBuilder::http3_max_field_section_size()` to configure the
maximum response headers.
- Add `ClientBuilder::tcp_keepalive_interval()` to configure TCP probe
interval.
- Add `ClientBuilder::tcp_keepalive_retries()` to configure TCP probe
count.
- Add `Proxy::headers()` to add extra headers that should be sent to a
proxy.
- Fix `redirect::Policy::limit()` which had an off-by-1 error, allowing
1 more redirect than specified.
- Fix HTTP/3 to support streaming request bodies.
- (wasm) Fix null bodies when calling `Response::bytes_stream()`.

#### v0.12.15

- Fix Windows to support both `ProxyOverride` and `NO_PROXY`.
- Fix http3 to support streaming response bodies.
- Fix http3 dependency from public API misuse.

#### v0.12.14

- Fix missing `fetch_mode_no_cors()`, marking as deprecated when not on
WASM.

#### v0.12.13

- Add `Form::into_reader()` for blocking `multipart` forms.
- Add `Form::into_stream()` for async `multipart` forms.
- Add support for SOCKS4a proxies.
- Fix decoding responses with multiple zstd frames.
- Fix `RequestBuilder::form()` from overwriting a previously set
`Content-Type` header, like the other builder methods.
- Fix cloning of request timeout in `blocking::Request`.
- Fix http3 synchronization of connection creation, reducing unneccesary
extra connections.
- Fix Windows system proxy to use `ProxyOverride` as a `NO_PROXY` value.
- Fix blocking read to correctly reserve and zero read buffer.
- (wasm) Add support for request timeouts.
- (wasm) Fix `Error::is_timeout()` to return true when from a request
timeout.

#### v0.12.12

- (wasm) Fix compilation by not compiler `tokio/time` on WASM.

#### v0.12.11

- Fix decompression returning an error when HTTP/2 ends with an empty
data frame.

#### v0.12.10

- Add `ClientBuilder::connector_layer()` to allow customizing the
connector stack.
- Add `ClientBuilder::http2_max_header_list_size()` option.
- Fix propagating body size hint (`content-length`) information when
wrapping bodies.
- Fix decompression of chunked bodies so the connections can be reused
more often.

#### v0.12.9

- Add `tls::CertificateRevocationLists` support.
- Add crate features to enable webpki roots without selecting a rustls
provider.
- Fix `connection_verbose()` to output read logs.
- Fix `multipart::Part::file()` to automatically include content-length.
- Fix proxy to internally no longer cache system proxy settings.

#### v0.12.8

- Add support for SOCKS4 proxies.
- Add `multipart::Form::file()` method for adding files easily.
- Add `Body::wrap()` to wrap any `http_body::Body` type.
- Fix the pool configuration to use a timer to remove expired
connections.

#### v0.12.7

- Revert adding `impl Service<http::Request<_>>` for `Client`.

#### v0.12.6

- Add support for `danger_accept_invalid_hostnames` for `rustls`.
- Add `impl Service<http::Request<Body>>` for `Client` and `&'_ Client`.
- Add support for `!Sync` bodies in `Body::wrap_stream()`.
- Enable happy eyeballs when `hickory-dns` is used.
- Fix `Proxy` so that `HTTP(S)_PROXY` values take precedence over
`ALL_PROXY`.
- Fix `blocking::RequestBuilder::header()` from unsetting `sensitive` on
passed header values.

#### v0.12.5

- Add `blocking::ClientBuilder::dns_resolver()` method to change DNS
resolver in blocking client.
- Add `http3` feature back, still requiring `reqwest_unstable`.
- Add `rustls-tls-no-provider` Cargo feature to use rustls without a
crypto provider.
- Fix `Accept-Encoding` header combinations.
- Fix http3 resolving IPv6 addresses.
- Internal: upgrade to rustls 0.23.

#### v0.12.4

- Add `zstd` support, enabled with `zstd` Cargo feature.
- Add `ClientBuilder::read_timeout(Duration)`, which applies the
duration for each read operation. The timeout resets after a successful
read.

#### v0.12.3

- Add `FromStr` for `dns::Name`.
- Add `ClientBuilder::built_in_webpki_certs(bool)` to enable them
separately.
- Add `ClientBuilder::built_in_native_certs(bool)` to enable them
separately.
- Fix sending `content-length: 0` for GET requests.
- Fix response body `content_length()` to return value when timeout is
configured.
- Fix `ClientBuilder::resolve()` to use lowercase domain names.

#### v0.12.2

- Fix missing ALPN when connecting to socks5 proxy with rustls.
- Fix TLS version limits with rustls.
- Fix not detected ALPN h2 from server with native-tls.

#### v0.12.1

- Fix `ClientBuilder::interface()` when no TLS is enabled.
- Fix `TlsInfo::peer_certificate()` being truncated with rustls.
- Fix panic if `http2` feature disabled but TLS negotiated h2 in ALPN.
- Fix `Display` for `Error` to not include its source error.

</details>

<details>
<summary>TrueLayer/reqwest-middleware (reqwest-middleware)</summary>

###
[`v0.5.1`](https://redirect.github.com/TrueLayer/reqwest-middleware/releases/tag/reqwest-middleware-v0.5.1)

[Compare
Source](https://redirect.github.com/TrueLayer/reqwest-middleware/compare/reqwest-middleware-v0.5.0...reqwest-middleware-v0.5.1)

##### Other

- Set changelog version for last release
([#&#8203;268](https://redirect.github.com/TrueLayer/reqwest-middleware/pull/268))

###
[`v0.5.0`](https://redirect.github.com/TrueLayer/reqwest-middleware/releases/tag/reqwest-middleware-v0.5.0)

[Compare
Source](https://redirect.github.com/TrueLayer/reqwest-middleware/compare/reqwest-middleware-v0.4.2...reqwest-middleware-v0.5.0)

##### Added

- Deprecated `fetch_mode_no_cors` as it's been deprecated in reqwest.

</details>

<details>
<summary>Peternator7/strum (strum)</summary>

###
[`v0.28.0`](https://redirect.github.com/Peternator7/strum/blob/HEAD/CHANGELOG.md#0280)

[Compare
Source](https://redirect.github.com/Peternator7/strum/compare/v0.27.2...v0.28.0)

- [#&#8203;461](https://redirect.github.com/Peternator7/strum/pull/461):
Allow any kind of passthrough attributes on `EnumDiscriminants`.
- Previously only list-style attributes (e.g.
`#[strum_discriminants(derive(...))]`) were supported. Now path-only
(e.g. `#[strum_discriminants(non_exhaustive)]`) and name/value (e.g.
`#[strum_discriminants(doc = "foo")]`)
    attributes are also supported.

- [#&#8203;462](https://redirect.github.com/Peternator7/strum/pull/462):
Add missing `#[automatically_derived]` to generated impls not
covered by
[#&#8203;444](https://redirect.github.com/Peternator7/strum/pull/444).

- [#&#8203;466](https://redirect.github.com/Peternator7/strum/pull/466):
Bump MSRV to 1.71, required to keep up with updated `syn` and
`windows-sys` dependencies. This is a breaking change if you're on an
old version of rust.

- [#&#8203;469](https://redirect.github.com/Peternator7/strum/pull/469):
Use absolute paths in generated proc macro code to avoid
  potential name conflicts.

- [#&#8203;465](https://redirect.github.com/Peternator7/strum/pull/465):
Upgrade `phf` dependency to v0.13.

- [#&#8203;473](https://redirect.github.com/Peternator7/strum/pull/473):
Fix `cargo fmt` / `clippy` issues and add GitHub Actions CI.

- [#&#8203;477](https://redirect.github.com/Peternator7/strum/pull/477):
`strum::ParseError` now implements `core::fmt::Display` instead
`std::fmt::Display` to make it `#[no_std]` compatible. Note the `Error`
trait wasn't available in core until `1.81`
  so `strum::ParseError` still only implements that in std.

- [#&#8203;476](https://redirect.github.com/Peternator7/strum/pull/476):
**Breaking Change** - `EnumString` now implements `From<&str>`
(infallible) instead of `TryFrom<&str>` when the enum has a
`#[strum(default)]` variant. This more accurately
reflects that parsing cannot fail in that case. If you need the old
`TryFrom` behavior, you can opt back in using
  `parse_error_ty` and `parse_error_fn`:

  ```rust
  #[derive(EnumString)]
#[strum(parse_error_ty = strum::ParseError, parse_error_fn =
make_error)]
  pub enum Color {
      Red,
      #[strum(default)]
      Other(String),
  }

  fn make_error(x: &str) -> strum::ParseError {
      strum::ParseError::VariantNotFound
  }
  ```

- [#&#8203;431](https://redirect.github.com/Peternator7/strum/pull/431):
Fix bug where `EnumString` ignored the `parse_err_ty`
  attribute when the enum had a `#[strum(default)]` variant.

- [#&#8203;474](https://redirect.github.com/Peternator7/strum/pull/474):
EnumDiscriminants will now copy `default` over from the
  original enum to the Discriminant enum.

  ```rust
  #[derive(Debug, Default, EnumDiscriminants)]
  #[strum_discriminants(derive(Default))] // <- Remove this in 0.28.
  enum MyEnum {
      #[default] // <- Will be the #[default] on the MyEnumDiscriminant
      #[strum_discriminants(default)] // <- Remove this in 0.28
      Variant0,
      Variant1 { a: NonDefault },
  }
  ```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - Only on Monday ( * * * * 1 ) (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/Glatzel/toolbox).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My42Ni40IiwidXBkYXRlZEluVmVyIjoiNDMuNjYuNCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>